import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional
from src.config.config import config

logger = logging.getLogger(__name__)


class EmailAlerts:
    def __init__(self):
        self.from_email = config.EMAIL.FROM
        self.password = config.EMAIL.PASSWORD
        self.to_email = config.EMAIL.TO
        self.smtp_server = config.EMAIL.SMTP_SERVER
        self.smtp_port = config.EMAIL.SMTP_PORT
        self.enabled = config.EMAIL.ENABLED
        
        if self.enabled and self.from_email and self.password:
            logger.info(f"Email alerts configured: {self.from_email} -> {self.to_email}")
        else:
            logger.warning("Email alerts disabled or not configured")
    
    def send_email(self, subject: str, body: str) -> bool:
        if not self.enabled or not self.from_email or not self.password:
            logger.debug("Email alerts disabled or not configured")
            return False
            
        try:
            msg = MIMEMultipart()
            msg['From'] = self.from_email
            msg['To'] = self.to_email
            msg['Subject'] = subject
            
            msg.attach(MIMEText(body, 'plain'))
            
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.from_email, self.password)
                server.send_message(msg)
                
            logger.info(f"Email sent: {subject}")
            return True
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            return False
    
    def send_trade_alert(self, signal_type: str, entry_price: float, 
                        stop_loss: float, take_profit: float,
                        strategy: str, reason: str) -> bool:
        if not self.enabled:
            return False
            
        subject = f"🥇 GOLD TRADE: {signal_type} - {strategy}"
        body = f"""
GOLD TRADE ALERT
{'=' * 50}

Strategy: {strategy}
Signal: {signal_type}
Entry Price: ${entry_price:.2f}
Stop Loss: ${stop_loss:.2f}
Take Profit: ${take_profit:.2f}
Reason: {reason}

{'=' * 50}
Generated by: Gold Trading Bot
"""
        
        return self.send_email(subject, body)
    
    def send_position_closed(self, entry_price: float, exit_price: float,
                           profit: float, strategy: str, reason: str) -> bool:
        if not self.enabled:
            return False
            
        status = "PROFIT" if profit > 0 else "LOSS"
        subject = f"💰 POSITION CLOSED: {status} - ${profit:.2f}"
        profit_percent = (profit / (entry_price * 100)) * 100
        body = f"""
POSITION CLOSED ALERT
{'=' * 50}

Strategy: {strategy}
Entry Price: ${entry_price:.2f}
Exit Price: ${exit_price:.2f}
Profit/Loss: ${profit:.2f} ({profit_percent:.2f}%)
Reason: {reason}

{'=' * 50}
Generated by: Gold Trading Bot
"""
        
        return self.send_email(subject, body)
    
    def send_daily_summary(self, date: str, balance: float, profit: float,
                          trades_count: int, win_rate: float) -> bool:
        if not self.enabled:
            return False
            
        subject = f"📊 DAILY SUMMARY: {date}"
        profit_percent = (profit / (balance - profit)) * 100 if balance != profit else 0
        body = f"""
DAILY TRADING SUMMARY
{'=' * 50}

Date: {date}
Starting Balance: ${balance - profit:.2f}
Current Balance: ${balance:.2f}
Daily P&L: ${profit:.2f} ({profit_percent:.2f}%)
Number of Trades: {trades_count}
Win Rate: {win_rate:.2%}

{'=' * 50}
Generated by: Gold Trading Bot
"""
        
        return self.send_email(subject, body)
    
    def send_weekly_report(self, week_start: str, week_end: str, 
                          week_profit: float, week_trades: int,
                          max_drawdown: float) -> bool:
        if not self.enabled:
            return False
            
        subject = f"📈 WEEKLY REPORT: {week_start} to {week_end}"
        body = f"""
WEEKLY TRADING REPORT
{'=' * 50}

Week: {week_start} to {week_end}
Weekly Profit: ${week_profit:.2f}
Total Trades: {week_trades}
Max Drawdown: {max_drawdown:.2%}

{'=' * 50}
Generated by: Gold Trading Bot
"""
        
        return self.send_email(subject, body)
    
    def send_error_alert(self, error: str, context: str = "") -> bool:
        if not self.enabled:
            return False
            
        subject = "❌ ERROR ALERT"
        body = f"""
ERROR ALERT
{'=' * 50}

Error: {error}

Context:
{context}

{'=' * 50}
Generated by: Gold Trading Bot
"""
        
        return self.send_email(subject, body)
    
    def send_risk_alert(self, alert_type: str, value: float, limit: float) -> bool:
        if not self.enabled:
            return False
            
        subject = f"⚠️ RISK ALERT: {alert_type}"
        body = f"""
RISK MANAGEMENT ALERT
{'=' * 50}

Alert Type: {alert_type}
Current Value: {value:.2%}
Limit: {limit:.2%}
Status: {'⚠️ LIMIT REACHED' if value >= limit else 'ℹ️ WARNING'}

{'=' * 50}
Generated by: Gold Trading Bot
"""
        
        return self.send_email(subject, body)
    
    def send_system_status(self, bot_running: bool, mt5_connected: bool,
                          balance: float, open_positions: int) -> bool:
        if not self.enabled:
            return False
            
        status = "RUNNING" if bot_running else "STOPPED"
        connection = "CONNECTED" if mt5_connected else "DISCONNECTED"
        subject = f"🤖 SYSTEM STATUS: {status}"
        body = f"""
SYSTEM STATUS UPDATE
{'=' * 50}

Bot Status: {status}
MT5 Connection: {connection}
Account Balance: ${balance:.2f}
Open Positions: {open_positions}

{'=' * 50}
Generated by: Gold Trading Bot
"""
        
        return self.send_email(subject, body)


email_alerts = EmailAlerts()
